const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2);
const fmt=d=>new Intl.DateTimeFormat('de-DE',{dateStyle:'medium'}).format(new Date(d));
const today=()=>new Date().toISOString().slice(0,10);
let db, state={view:'home',tankId:null,tab:'dashboard',calDate:new Date(),products:[]};
const defaults={settings:{waterStep:5},tanks:[],entries:[],products:[]};
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('aquatracker2',1);r.onupgradeneeded=()=>{const d=r.result;['settings','tanks','entries','products'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'})})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function all(store){return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,obj){return new Promise((res,rej)=>{const r=db.transaction(store,'readwrite').objectStore(store).put(obj);r.onsuccess=()=>res(obj);r.onerror=()=>rej(r.error)})}
function del(store,id){return new Promise((res,rej)=>{const r=db.transaction(store,'readwrite').objectStore(store).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function load(){state.tanks=await all('tanks');state.entries=await all('entries');state.products=await all('products');const settings=(await all('settings'))[0];state.settings=settings||{id:'main',waterStep:5};if(!settings)await put('settings',state.settings);if(!state.products.length){const list=await fetch('products.json').then(r=>r.json());for(const p of list){await put('products',{id:uid(),...p,active:['Plant System V30','Plant System S7','Plant System E15','Aqua Elixir','Bacto Elixir Bio'].includes(p.name),stock:null,custom:false})}state.products=await all('products')}}
function setView(v){state.view=v;$$('.view').forEach(x=>x.classList.remove('active'));$('#'+v+'View').classList.add('active');$$('footer button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#backBtn').classList.toggle('hidden',v!=='tank');$('#title').textContent=v==='tank'?(tank()?.name||'Aquarium'):'AquaTracker';$('#subtitle').textContent=v==='tank'?`${tank()?.volume||'?'} Liter`:(v==='settings'?'Produkte & Einstellungen':'Meine Aquarien');render()}
const tank=()=>state.tanks.find(t=>t.id===state.tankId);
function render(){if(state.view==='home')renderHome();if(state.view==='tank')renderTank();if(state.view==='settings')renderSettings()}
function renderHome(){const g=$('#tankGrid');if(!state.tanks.length){g.innerHTML='<div class="empty"><div style="font-size:50px">🐠</div><h3>Noch kein Aquarium</h3><p>Lege dein erstes Becken an.</p></div>';return}g.innerHTML=state.tanks.map(t=>{const e=state.entries.filter(x=>x.tankId===t.id),last=e.filter(x=>x.type==='cleaning').sort((a,b)=>b.date.localeCompare(a.date))[0];return `<article class="tankCard" data-id="${t.id}">${t.photo?`<img src="${t.photo}" alt="">`:'<div class="tankPlaceholder">🐠</div>'}<div class="tankCardBody"><h3>${esc(t.name)}</h3><div class="meta">${t.volume||'–'} Liter · ${esc(t.location||'Kein Standort')}</div><div class="tankStats"><span class="pill">💧 ${last?fmt(last.date):'noch nie'}</span><span class="pill">📝 ${e.length}</span></div></div></article>`}).join('');$$('.tankCard').forEach(c=>c.onclick=()=>{state.tankId=c.dataset.id;setView('tank')})}
function renderTank(){const t=tank();if(!t)return setView('home');const hero=$('#tankHero');hero.style.backgroundImage=t.photo?`linear-gradient(transparent,#062d3ccc),url(${t.photo})`:'';hero.innerHTML=`<div><h2>${esc(t.name)}</h2><div>${t.volume||'–'} Liter${t.location?' · '+esc(t.location):''}</div></div>`;$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));if(state.tab==='dashboard')renderDashboard();if(state.tab==='calendar')renderCalendar();if(state.tab==='history')renderHistory()}
function renderDashboard(){const e=state.entries.filter(x=>x.tankId===state.tankId);const last=type=>e.filter(x=>x.type===type).sort((a,b)=>b.date.localeCompare(a.date))[0];const stocks=state.products.filter(p=>p.active&&p.stock).sort((a,b)=>(a.stock.remaining/a.stock.size)-(b.stock.remaining/b.stock.size)).slice(0,4);$('#tabContent').innerHTML=`<div class="cards"><article class="card metric"><span>Letzte Reinigung</span><strong>${last('cleaning')?fmt(last('cleaning').date):'–'}</strong></article><article class="card metric"><span>Letzte Filterreinigung</span><strong>${last('filter')?fmt(last('filter').date):'–'}</strong></article><article class="card metric"><span>Letzte Analyse</span><strong>${last('analysis')?fmt(last('analysis').date):'–'}</strong></article><article class="card metric"><span>Einträge gesamt</span><strong>${e.length}</strong></article></div><h3>Flaschenbestand (gemeinsam)</h3><div class="cards">${stocks.length?stocks.map(stockCard).join(''):'<article class="card">Noch keine Flaschen erfasst.</article>'}</div>`}
function stockCard(p){const pc=Math.max(0,Math.round(p.stock.remaining/p.stock.size*100));return `<article class="card"><b>🧴 ${esc(p.name)}</b><div class="meta">${num(p.stock.remaining)} von ${num(p.stock.size)} ${p.unit}</div><div class="progress"><i style="width:${pc}%"></i></div><strong>${pc} %</strong></article>`}
function renderCalendar(){const d=state.calDate,y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-((first.getDay()+6)%7));let days='';for(let i=0;i<42;i++){const x=new Date(start);x.setDate(start.getDate()+i);const iso=x.toISOString().slice(0,10),ev=state.entries.filter(e=>e.tankId===state.tankId&&e.date===iso);days+=`<div class="day ${x.getMonth()!==m?'other':''} ${iso===today()?'today':''}"><div class="dayNum">${x.getDate()}</div><div class="events">${ev.map(e=>`<span class="eventIcon" title="${label(e.type)}">${icon(e.type)}</span>`).join('')}</div></div>`}$('#tabContent').innerHTML=`<article class="card"><div class="calendarHead"><button id="prevMonth">←</button><h3>${new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(d)}</h3><button id="nextMonth">→</button></div><div class="calendar">${['Mo','Di','Mi','Do','Fr','Sa','So'].map(x=>`<div class="weekday">${x}</div>`).join('')}${days}</div></article>`;$('#prevMonth').onclick=()=>{state.calDate=new Date(y,m-1,1);renderCalendar()};$('#nextMonth').onclick=()=>{state.calDate=new Date(y,m+1,1);renderCalendar()}}
function renderHistory(){const es=state.entries.filter(e=>e.tankId===state.tankId).sort((a,b)=>(b.date+b.created).localeCompare(a.date+a.created));$('#tabContent').innerHTML=`<article class="card">${es.length?es.map(e=>`<div class="historyItem"><div class="historyIcon">${icon(e.type)}</div><div><h4>${label(e.type)} · ${fmt(e.date)}</h4><p>${summary(e)}</p></div><button class="danger" data-del="${e.id}">Löschen</button></div>`).join(''):'Noch keine Einträge.'}</article>`;$$('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Eintrag wirklich löschen?')){await del('entries',b.dataset.del);state.entries=await all('entries');renderHistory()}})}
function summary(e){if(e.type==='cleaning')return `${e.water||0} L Wasserwechsel${e.notes?' · '+e.notes:''}`;if(e.type==='filter')return `${e.filterName||'Filter'}${e.notes?' · '+e.notes:''}`;return ['pH','KH','GH','NO2','NO3','PO4','Fe','Leitwert','Temperatur'].filter(k=>e.values?.[k]).map(k=>`${k}: ${e.values[k]}`).join(' · ')||e.notes||'Analyse'}
function renderSettings(){$('#waterStep').value=state.settings.waterStep||5;const groups={};state.products.forEach(p=>(groups[p.category]??=[]).push(p));$('#productList').innerHTML=Object.entries(groups).sort().map(([g,ps])=>`<h4>${esc(g)}</h4>${ps.sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<div class="productRow"><input type="checkbox" data-product="${p.id}" ${p.active?'checked':''}><div><b>${esc(p.name)}</b><small>${p.unit}${p.pumpMl?' · 1 Hub ≈ '+p.pumpMl+' ml':''}</small></div><button class="bottle" data-bottle="${p.id}" title="Flasche verwalten">🧴</button></div>`).join('')}`).join('');$('#stockList').innerHTML=state.products.filter(p=>p.stock).map(p=>{const pc=Math.round(p.stock.remaining/p.stock.size*100);return `<div class="stockRow"><span>🧴</span><div><b>${esc(p.name)}</b><small>${num(p.stock.remaining)} / ${num(p.stock.size)} ${p.unit}</small><div class="progress"><i style="width:${pc}%"></i></div></div><strong>${pc}%</strong></div>`}).join('')||'Noch keine Flasche erfasst.';$$('[data-product]').forEach(x=>x.onchange=async()=>{const p=state.products.find(p=>p.id===x.dataset.product);p.active=x.checked;await put('products',p)});$$('[data-bottle]').forEach(x=>x.onclick=()=>bottleDialog(x.dataset.bottle))}
function openDialog(html,onSave){$('#modalBody').innerHTML=html;const dlg=$('#modal');dlg.showModal();$('#modalForm').onsubmit=async ev=>{ev.preventDefault();if(await onSave(new FormData(ev.target))!==false)dlg.close()}}
function tankDialog(){openDialog(`<h2>Neues Aquarium</h2><label>Name<input name="name" required placeholder="z. B. Wohnzimmer"></label><label>Größe in Litern<input name="volume" type="number" min="1" required></label><label>Standort<input name="location"></label><label>Filter<input name="filter"></label><label>Besatz<textarea name="stock"></textarea></label><label>Foto<input name="photo" type="file" accept="image/*"></label>`,async f=>{const file=f.get('photo'),photo=file?.size?await fileData(file):'';const t={id:uid(),name:f.get('name'),volume:+f.get('volume'),location:f.get('location'),filter:f.get('filter'),stock:f.get('stock'),photo,created:new Date().toISOString()};await put('tanks',t);state.tanks=await all('tanks');renderHome()})}
function entryDialog(type){if(type==='cleaning')cleaningDialog();if(type==='filter')filterDialog();if(type==='analysis')analysisDialog()}
function cleaningDialog(){const ps=state.products.filter(p=>p.active);openDialog(`<h2>💧 Reinigung</h2><label>Datum<input name="date" type="date" value="${today()}" required></label><label>Wasserwechsel in Litern<input name="water" type="number" min="0" step="${state.settings.waterStep||5}" value="${state.settings.waterStep||5}"></label><h3>Verwendete Produkte</h3>${ps.map(p=>`<div class="productDose"><label class="check"><input name="use_${p.id}" type="checkbox">${esc(p.name)}</label><div><label>Menge (${p.unit})<input name="dose_${p.id}" type="number" min="0" step="0.1"></label></div></div>`).join('')||'<p>Aktiviere zuerst Produkte im Produktmenü.</p>'}<label>Notizen<textarea name="notes"></textarea></label>`,async f=>{const doses=[];for(const p of ps){if(f.get('use_'+p.id)){const amount=+(f.get('dose_'+p.id)||0);doses.push({productId:p.id,name:p.name,amount,unit:p.unit});if(amount&&p.stock){p.stock.remaining=Math.max(0,p.stock.remaining-amount);await put('products',p)}}}await saveEntry({type:'cleaning',date:f.get('date'),water:+f.get('water'),doses,notes:f.get('notes')})})}
function filterDialog(){const t=tank();openDialog(`<h2>🧽 Filterreinigung</h2><label>Datum<input name="date" type="date" value="${today()}" required></label><label>Filter<input name="filterName" value="${esc(t.filter||'')}"></label>${['Vorfilter gereinigt','Filterschwämme gereinigt','Filtermedien gewechselt','Schläuche gereinigt','Rotor gereinigt'].map((x,i)=>`<label class="check"><input type="checkbox" name="task${i}">${x}</label>`).join('')}<label>Notizen<textarea name="notes"></textarea></label>`,async f=>saveEntry({type:'filter',date:f.get('date'),filterName:f.get('filterName'),tasks:[0,1,2,3,4].filter(i=>f.get('task'+i)),notes:f.get('notes')}))}
function analysisDialog(){const fields=['pH','KH','GH','NO2','NO3','PO4','Fe','Leitwert','TDS','Temperatur','CO2'];openDialog(`<h2>🧪 Wasseranalyse</h2><label>Datum<input name="date" type="date" value="${today()}" required></label><div class="cards">${fields.map(x=>`<label>${x}<input name="${x}" type="number" step="0.01"></label>`).join('')}</div><label>Notizen<textarea name="notes"></textarea></label>`,async f=>{const values={};fields.forEach(x=>{if(f.get(x)!=='')values[x]=f.get(x)});await saveEntry({type:'analysis',date:f.get('date'),values,notes:f.get('notes')})})}
async function saveEntry(e){await put('entries',{id:uid(),tankId:state.tankId,created:new Date().toISOString(),...e});state.entries=await all('entries');state.products=await all('products');renderTank()}
function bottleDialog(id){const p=state.products.find(p=>p.id===id),s=p.stock||{};openDialog(`<h2>🧴 ${esc(p.name)}</h2><p>Frische Flasche oder aktuellen Bestand eintragen.</p><label>Flaschengröße (${p.unit})<input name="size" type="number" min="0" step="0.1" value="${s.size||''}" required></label><label>Aktueller Inhalt (${p.unit})<input name="remaining" type="number" min="0" step="0.1" value="${s.remaining??s.size??''}" required></label><label>Menge pro Hub (ml)<input name="pumpMl" type="number" min="0" step="0.1" value="${p.pumpMl||''}"></label>`,async f=>{p.stock={size:+f.get('size'),remaining:+f.get('remaining'),opened:new Date().toISOString()};p.pumpMl=+(f.get('pumpMl')||0);await put('products',p);state.products=await all('products');renderSettings()})}
function customProductDialog(){openDialog(`<h2>Eigenes Produkt</h2><label>Name<input name="name" required></label><label>Kategorie<input name="category" value="Eigenes Produkt"></label><label>Einheit<select name="unit"><option>ml</option><option>g</option><option>Tablette</option><option>Hub</option></select></label>`,async f=>{await put('products',{id:uid(),name:f.get('name'),category:f.get('category'),unit:f.get('unit'),active:true,stock:null,custom:true});state.products=await all('products');renderSettings()})}
function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function exportData(){const data={version:2,exported:new Date().toISOString(),tanks:await all('tanks'),entries:await all('entries'),products:await all('products'),settings:await all('settings')};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='AquaTracker-Backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)}
async function importData(file){const data=JSON.parse(await file.text());for(const s of ['tanks','entries','products','settings'])for(const x of data[s]||[])await put(s,x);await load();setView('home')}
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function icon(t){return t==='cleaning'?'💧':t==='filter'?'🧽':'🧪'}function label(t){return t==='cleaning'?'Reinigung':t==='filter'?'Filterreinigung':'Wasseranalyse'}function num(n){return new Intl.NumberFormat('de-DE',{maximumFractionDigits:1}).format(n||0)}
$('#addTankBtn').onclick=tankDialog;$('#shopBtn').onclick=()=>window.open('https://www.dennerle.com/','_blank','noopener');$('#backBtn').onclick=()=>setView('home');$$('footer button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('.tabs button').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;renderTank()});$$('[data-entry]').forEach(b=>b.onclick=()=>entryDialog(b.dataset.entry));$('#waterStep').onchange=async e=>{state.settings.waterStep=Math.max(1,+e.target.value||5);await put('settings',state.settings)};$('#addCustomProduct').onclick=customProductDialog;$('#exportBtn').onclick=exportData;$('#importInput').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);
(async()=>{await openDB();await load();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js')})().catch(e=>{console.error(e);alert('AquaTracker konnte nicht gestartet werden: '+e.message)});
